targets:
  $default:
    builders:

      source_gen|combining_builder:
        generate_for:

          # Models
          - lib/models/requests/**.dart
          - lib/models/responses/**.dart
          - lib/models/internal/**.dart
          - lib/models/props/**.dart

          # Providers
          - lib/providers/global/**.dart
          - lib/providers/pages/**.dart

          # Use cases
          - lib/use_cases/auth/**.dart
          - lib/use_cases/network/core/**.dart
          - lib/use_cases/network/executor/**.dart
          - lib/use_cases/network/rest_clients/**.dart
          - lib/use_cases/status/**.dart
          - lib/use_cases/pico/**.dart

        options:
          build_extensions:

            # Models
            '^lib/models/requests/{{}}.dart': 'lib/models/requests/generated/{{}}.g.dart'
            '^lib/models/responses/{{}}.dart': 'lib/models/responses/generated/{{}}.g.dart'
            '^lib/models/internal/{{}}.dart': 'lib/models/internal/generated/{{}}.g.dart'
            '^lib/models/props/{{}}.dart': 'lib/models/props/generated/{{}}.g.dart'

            # Providers
            '^lib/providers/global/{{}}.dart': 'lib/providers/global/generated/{{}}.g.dart'
            '^lib/providers/pages/{{}}.dart': 'lib/providers/pages/generated/{{}}.g.dart'

            # Use cases
            '^lib/use_cases/auth/{{}}.dart': 'lib/use_cases/auth/generated/{{}}.g.dart'
            '^lib/use_cases/network/core/{{}}.dart': 'lib/use_cases/network/core/generated/{{}}.g.dart'
            '^lib/use_cases/network/executor/{{}}.dart': 'lib/use_cases/network/executor/generated/{{}}.g.dart'
            '^lib/use_cases/network/rest_clients/{{}}.dart': 'lib/use_cases/network/rest_clients/generated/{{}}.g.dart'
            '^lib/use_cases/status/{{}}.dart': 'lib/use_cases/status/generated/{{}}.g.dart'
            '^lib/use_cases/pico/{{}}.dart': 'lib/use_cases/pico/generated/{{}}.g.dart'

      freezed|freezed:
        enabled: true
        options:
          build_extensions:

            # Models
            '^lib/models/requests/{{}}.dart': 'lib/models/requests/generated/{{}}.freezed.dart'
            '^lib/models/responses/{{}}.dart': 'lib/models/responses/generated/{{}}.freezed.dart'
            '^lib/models/internal/{{}}.dart': 'lib/models/internal/generated/{{}}.freezed.dart'
            '^lib/models/props/{{}}.dart': 'lib/models/props/generated/{{}}.freezed.dart'

            # Providers
            '^lib/providers/global/{{}}.dart': 'lib/providers/global/generated/{{}}.freezed.dart'
            '^lib/providers/pages/{{}}.dart': 'lib/providers/pages/generated/{{}}.freezed.dart'

            # Use cases
            '^lib/use_cases/auth/{{}}.dart': 'lib/use_cases/auth/generated/{{}}.freezed.dart'
            '^lib/use_cases/network/core/{{}}.dart': 'lib/use_cases/network/core/generated/{{}}.freezed.dart'
            '^lib/use_cases/network/executor/{{}}.dart': 'lib/use_cases/network/executor/generated/{{}}.freezed.dart'
            '^lib/use_cases/network/rest_clients/{{}}.dart': 'lib/use_cases/network/rest_clients/generated/{{}}.freezed.dart'
            '^lib/use_cases/status/{{}}.dart': 'lib/use_cases/status/generated/{{}}.freezed.dart'
            '^lib/use_cases/pico/{{}}.dart': 'lib/use_cases/pico/generated/{{}}.freezed.dart'

